## Day 1 Pytorch Fundamentals

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
print('Hello lets start learning pytorch')

Hello lets start learning pytorch


Creating tensors

In [ ]:
#scalars
scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [3]:
#tensor
tensor = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]],[[1,2,3],[2,2,1],[3,3,4]]])
tensor.ndim

3

In [4]:
tensor.shape

torch.Size([2, 3, 3])

In [6]:
#Random tensors - these are way to make deep nn learn starting with random and lookup data evaluate and again radomise loop
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)
print(tensor.dtype)

tensor([[0.1602, 0.9814, 0.1207, 0.7159],
        [0.2740, 0.3527, 0.8173, 0.3236],
        [0.2910, 0.1815, 0.2323, 0.8420]])
2
torch.int64


In [9]:
#zeros and ones
zeros_tensor = torch.zeros(3,4)
print(zeros_tensor)
zeros_tensor.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.float32

In [15]:
# range of tensors and tensors like
range_tensor = torch.arange(1,11, 1) # range is deprecated so use arange
print(range_tensor)
zeros_like = torch.zeros_like(range_tensor)
print(zeros_like)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Data types in tensors
This is where a lot of errors will be faced when it comes to pytorcha nd deep learning
1. tensors not in right datatype - if one tensor is float 32 and other is float16 we'll get errors
2. tensors not in right device - if one tensor is in cuda and other in cpu
3. tensors not in right shape - one is 8 and otehr is 10


In [17]:
# tensor datatypes
# flat32 tensor
float_32_tensor = torch.tensor([3.0,4.0,5.0], dtype=None) # even if we specify None torch will emit float 32
print(float_32_tensor)
float_16_tensor = torch.tensor([3.0,5.0,7.0], dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)
tensor_params = torch.tensor([1.0,2.0,3.0], dtype=None, device=None, requires_grad=False) # whether to track gradients with this tensor operation (requires_grad)


tensor([3., 4., 5.])
tensor([3., 5., 7.], dtype=torch.float16)
torch.float16


In [22]:
# type conversion
float32_tensor = torch.tensor([10,20], dtype=None)
float16_tensor = float32_tensor.type(torch.float16)
mul = float32_tensor * float16_tensor
print(mul) # it works looks like our rule is wrong - we'll get errors if we are not in same datatype

tensor([100., 400.], dtype=torch.float16)
