## Day 1 Pytorch Fundamentals

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
print('Hello lets start learning pytorch')

Hello lets start learning pytorch


Creating tensors

In [ ]:
#scalars
scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#tensor
tensor = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]],[[1,2,3],[2,2,1],[3,3,4]]])
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([2, 3, 3])

In [ ]:
#Random tensors - these are way to make deep nn learn starting with random and lookup data evaluate and again radomise loop
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)
print(tensor.dtype)

tensor([[0.7118, 0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770]])
2
torch.int64


In [ ]:
#zeros and ones
zeros_tensor = torch.zeros(3,4)
print(zeros_tensor)
zeros_tensor.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.float32

In [ ]:
# range of tensors and tensors like
range_tensor = torch.arange(1,11, 1) # range is deprecated so use arange
print(range_tensor)
zeros_like = torch.zeros_like(range_tensor)
print(zeros_like)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Data types in tensors
This is where a lot of errors will be faced when it comes to pytorcha nd deep learning
1. tensors not in right datatype - if one tensor is float 32 and other is float16 we'll get errors
2. tensors not in right device - if one tensor is in cuda and other in cpu
3. tensors not in right shape - one is 8 and otehr is 10


In [ ]:
# tensor datatypes
# flat32 tensor
float_32_tensor = torch.tensor([3.0,4.0,5.0], dtype=None) # even if we specify None torch will emit float 32
print(float_32_tensor)
float_16_tensor = torch.tensor([3.0,5.0,7.0], dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)
tensor_params = torch.tensor([1.0,2.0,3.0], dtype=None, device=None, requires_grad=False) # whether to track gradients with this tensor operation (requires_grad)


tensor([3., 4., 5.])
tensor([3., 5., 7.], dtype=torch.float16)
torch.float16


In [ ]:
# type conversion
float32_tensor = torch.tensor([10,20], dtype=None)
float16_tensor = float32_tensor.type(torch.float16)
mul = float32_tensor * float16_tensor
print(mul) # it works looks like our rule is wrong - we'll get errors if we are not in right datatype but actually its only for same datatype diff dt still throws errpr


tensor([100., 400.], dtype=torch.float16)


# manipulating tensors (tensor operations)
tensor operations include add, sub, mul (element-wise), div

In [ ]:
tensoradd = torch.tensor([1,2,3])
tensoradd = tensoradd.add(10)
print(tensoradd)

tensor([11, 12, 13])


In [ ]:
tensorsub = torch.tensor([1,2,3])
tensorsub = tensorsub.sub(1)
print(tensorsub)

tensor([0, 1, 2])


In [ ]:
# tensor multiplication
# Element wise mul
elmul_tensor = torch.tensor([1,2,3])
print(f"Element wise mul{elmul_tensor * elmul_tensor}")
matmul_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"Matrix mul{torch.matmul(matmul_tensor, matmul_tensor)}")


Element wise multensor([1, 4, 9])
Matrix multensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [ ]:
# comparing time it takes between normal matrix mul vs tensor matrix multiplication
%%time
time1 = torch.tensor([1,2,3])
matmulres1 = 0
for i in range(len(time1)):
  matmulres1 += time1[i] * time1[i]
print(matmulres1)

tensor(14)
CPU times: user 809 µs, sys: 0 ns, total: 809 µs
Wall time: 1.27 ms


In [ ]:
%%time
time2 = torch.tensor([1,2,3])
torch.matmul(time2, time2)

CPU times: user 102 µs, sys: 7 µs, total: 109 µs
Wall time: 114 µs


tensor(14)

# Rules of matrix multiplication
1. Inner dimesnions mutch match or else we will get into error
eg (2,3) (3,2) will work and not (3,2) and (3,2)
2. The resultant matrix will always have the ouyter shape of the matrix
for example (2,3) and (3,2) will result in 2X2 matrix and even (3,10) and (10,3) will result in 3X3 matrix

Transpose

In [ ]:
# to solve matrix shape problems lets transpose the matrix to fix the issues
matrix_a = torch.tensor([[1,2,3],[3,4,5]])
matrix_b = torch.tensor([[1,2,3],[3,4,5]]) # 3x2 matrix
print(torch.matmul(matrix_a, matrix_b.T))


tensor([[14, 26],
        [26, 50]])


Tensor Aggregation
Finding the min, max, mean and sum

In [ ]:
x = torch.arange(0,100,10)
print(x)
print(x.min(), torch.min(x))
print(x.max(), torch.max(x))
print(x.type(torch.float32).mean(), torch.mean(x.type(torch.float32)))
print(x.sum(), torch.sum(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


In [ ]:
# index of min and max
x = torch.arange(0,100,10)
print(torch.argmin(x), torch.argmax(x))

tensor(0) tensor(9)


Reshaping, stacking, squeezing and unsqueezing tensors
1. Reshaping - reshapes an input tensor to a defined shape
2. View - Return a view of the input tensor of certain shape but keep the same memory as the original tensor
3. Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
4. Squeeze - removes all '1' dimesnions from the sensor
5. Unsquueze - add a '1' dimensions to a target tensor
6. Permute - return a view of the input with dimensions permuted (swapped) in a certain way



In [ ]:
x = torch.arange(0., 10.)
print(x, x.shape)
# reshape would only work if you dont shape the size of the original tensor
x_reshape1 = x.reshape(5,2)
print(x_reshape1, x_reshape1.shape)
x_reshape2 = x.reshape(2,5)
print(x_reshape2, x_reshape2.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([10])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]]) torch.Size([5, 2])
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]) torch.Size([2, 5])


In [ ]:
# view takes a deep copy of original tensor so any changes to view tensor will change the original tensor as well
tensor = torch.arange(0.,10.)
print(tensor, tensor.shape)
tensor_view = tensor.view(5,2)
print(tensor_view, tensor_view.shape)
tensor_view[:,0] = 5 # changes all 0th index of all vectors to 5
print(tensor_view, tensor_view.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([10])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]]) torch.Size([5, 2])
tensor([[5., 1.],
        [5., 3.],
        [5., 5.],
        [5., 7.],
        [5., 9.]]) torch.Size([5, 2])


In [ ]:
# stack tensors on top of each other
tensor = torch.arange(0.,10.)
print(tensor, tensor.shape)
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=1)
print(tensor_stacked, tensor_stacked.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([10])
tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]]) torch.Size([10, 3])


In [ ]:
# squeeze tensors - remove all single dimesions from a target tensor
tensor = torch.tensor([[3],[5],[7]])
print(tensor, tensor.squeeze())
print(tensor.shape, tensor.squeeze().shape)

tensor([[3],
        [5],
        [7]]) tensor([3, 5, 7])
torch.Size([3, 1]) torch.Size([3])


In [ ]:
# unsqueee tensors - add omne dimension to the target tensor
tensor = torch.tensor([1,2,3,5,6,7,8,9])
print(tensor, tensor.unsqueeze(dim=0))
print(tensor, tensor.unsqueeze(dim=1))

tensor([1, 2, 3, 5, 6, 7, 8, 9]) tensor([[1, 2, 3, 5, 6, 7, 8, 9]])
tensor([1, 2, 3, 5, 6, 7, 8, 9]) tensor([[1],
        [2],
        [3],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [ ]:
# permute tensors - rearrange the dimensions in the tensor in a specific way
original_tensor = torch.rand(size=(224,224,3))
print(original_tensor.shape)
permuted_tensor = original_tensor.permute(2,0,1)
print(permuted_tensor.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


Pytorch and Numpy

Numpy is popular scientific puthon numerical computing library so
Pytorch has compatibility to load data from numpy and change tensor to numpy
torch.from_numpy(ndarray)
torch.Tensor.numpy()


In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting numpy default dtupe ios float 64 which will be passed to tensor
print(array, array.dtype, tensor)

[1. 2. 3. 4. 5. 6. 7.] float64 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


Numpy and torch tensor doesnt share memory which means one value does not change the other
And default type of tensor float32 will be applied to numpy if we convert to that

## Pytorch reproducability ( taking out the random out of random)

in short how a newural network leans is:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again -> again...`


To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

Pseudo randomness - random without any means just the rand method

In [ ]:
import torch

# create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

RANDOM_SEED = 100
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.2089, 0.7017, 0.5200, 0.8843],
        [0.8486, 0.7041, 0.1515, 0.7470],
        [0.5887, 0.6700, 0.1507, 0.5938]])
tensor([[0.2676, 0.2770, 0.5603, 0.8046],
        [0.0534, 0.1003, 0.1376, 0.5909],
        [0.5555, 0.4608, 0.7407, 0.1953]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and pytorch objects on GPUs (and making faster computations)
GPUs = faster computation on numbers, CUDA + NVIDIA hardware + pytorch

## Getting a GPU
1. Easiest - Google colab for free GPU (options to upgrade)
2. Setting your own GPU - takes effort and investment
3. use cloud
Foe 2,3 we need pytorch, gpu driver (CUDA)

In [ ]:
!nvidia-smi

Sun Jun 29 16:35:10 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Putting tensors and models on gpu
Main reason it is faster for computation

In [109]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu, tensor_back_on_cpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0
[1 2 3] cpu
